name: "Build test infrastructure"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.05:home-manager=https://github.com/nix-community/home-manager/archive/release-22.05.tar.gz
    - run: tests/build.sh
