name: "Build test infrastructure"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-23.05:home-manager=https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz
        extra_nix_config: |
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.menou.me-1:xYMqGP/9BAKWIlONTERSaNX61H799tD25Xix7sp9Duc=
          substituters = https://cache.nixos.org/ https://cache.menou.me/
    - run: tests/build.sh
