name: "Lint"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        # Still 22.11 here because nix-linter is broken 23.05
        nix_path: nixpkgs=channel:nixos-22.11
    - run: lint/nix.sh
    - run: lint/shell.sh
